name=mnv-iot-sdk
version=1.1.2
author=MNV Team
maintainer=MNV Team <support@mnv.vn>
sentence=SDK kết nối an toàn cho hệ sinh thái MNV-IoT.
paragraph=Thư viện cung cấp khả năng xác thực thiết bị qua HTTPS, quản lý kết nối MQTT bằng JWT và hỗ trợ các tính năng cao cấp như LWT, RPC và Smart Telemetry cho ESP32.
category=Communication
url=https://github.com/kayandk/mnv-iot-sdk
architectures=esp32
includes=IoTClient.h
depends=PubSubClient, ArduinoJson
